import { Category } from "./types";
import { CategoryIcons } from "./CategoryIcons";

export const categories: Category[] = [
  {
    id: "laptop-gaming",
    name: "Laptop Gaming",
    slug: "laptop-gaming",
    productCount: 156,
    icon: CategoryIcons.laptop,
    gradient: "from-blue-500/10 to-indigo-500/10",
    image: "/images/categories/laptop.jpg",
  },
  {
    id: "pc-gaming",
    name: "PC Gaming",
    slug: "pc-gaming",
    productCount: 89,
    icon: CategoryIcons.pcGaming,
    gradient: "from-red-500/10 to-orange-500/10",
    image: "/images/categories/pc-gaming.jpg",
  },
  {
    id: "man-hinh",
    name: "Màn Hình",
    slug: "man-hinh",
    productCount: 128,
    icon: CategoryIcons.monitor,
    gradient: "from-purple-500/10 to-pink-500/10",
    image: "/images/categories/monitor.jpg",
  },
  {
    id: "ban-phim",
    name: "Bàn Phím",
    slug: "ban-phim",
    productCount: 76,
    icon: CategoryIcons.keyboard,
    gradient: "from-amber-500/10 to-yellow-500/10",
    image: "/images/categories/keyboard.jpg",
  },
  {
    id: "chuot",
    name: "Chuột Gaming",
    slug: "chuot",
    productCount: 94,
    icon: CategoryIcons.mouse,
    gradient: "from-cyan-500/10 to-blue-500/10",
    image: "/images/categories/mouse.jpg",
  },
  {
    id: "tai-nghe",
    name: "Tai Nghe",
    slug: "tai-nghe",
    productCount: 112,
    icon: CategoryIcons.headset,
    gradient: "from-rose-500/10 to-red-500/10",
    image: "/images/categories/headset.jpg",
  },
  {
    id: "thiet-bi-mang",
    name: "Thiết Bị Mạng",
    slug: "thiet-bi-mang",
    productCount: 67,
    icon: CategoryIcons.network,
    gradient: "from-violet-500/10 to-purple-500/10",
    image: "/images/categories/network.jpg",
  },
  {
    id: "linh-kien-pc",
    name: "Linh Kiện PC",
    slug: "linh-kien-pc",
    productCount: 203,
    icon: CategoryIcons.components,
    gradient: "from-slate-500/10 to-gray-500/10",
    image: "/images/categories/components.jpg",
  },
  {
    id: "ghe-gaming",
    name: "Ghế Gaming",
    slug: "ghe-gaming",
    productCount: 45,
    icon: CategoryIcons.chair,
    gradient: "from-orange-500/10 to-red-500/10",
    image: "/images/categories/chair.jpg",
  },
];
